compile:
	gcc server.c -o server -lpthread -I/usr/include/openssl/ -lcrypto -lssl
	gcc client1.c -o client1 -lpthread -I/usr/include/openssl/ -lcrypto -lssl
	gcc client2.c -o client2 -lpthread -I/usr/include/openssl/ -lcrypto -lssl